### ISSUE TITLE
Allow users to recover from or avoid accidental todo deletes

### ISSUE THREAD

**Issue by JonShort** [JonShort/tododay#9]
At the moment there's no way for users to recover from accidentally deleting a todo

Options would be:
* A) Allow the action to be reversed (with `cmd + z`)
* B) Prompt user to confirm delete

## Option A - preferred

By allowing users to recover, they're not impeded when they actually want to remove a todo.

`cmd + z` support is mandatory here because it's the "panic button" for desktop users

UI shouldn't be too intrusive or it could be annoying

![image](https://github.com/JonShort/tododay/assets/21317379/27f28ee2-cf66-420c-9459-0831e296f017)

### Implementation

This _could_ fit within the existing system without logic changes, by hooking into the delete click handler

![image](https://github.com/JonShort/tododay/assets/21317379/70295b62-feeb-4449-bd59-3e9a262f2f55)

## Option B

Adding a prompt could help to avoid accidental deletes by providing a way for the user to catch slips

This is quite intrusive, but would be justified given the destructive nature of the action

![image](https://github.com/JonShort/tododay/assets/21317379/d23315b8-1be5-4143-9ef6-4f3d7f8b9b9f)

**Comment by JonShort** [comment]
Idea from @jaysc and @O0mix0O - an in-mem storage (e.g. array) which temporarily stores removed todos.

A listener or watcher then uses this when the user chooses to "undo" a removal

Seems to be a good approach as the current "example implementation" diagram doesn't really accomodate for storing the removed item state anywhere

**Comment by jaysc** [comment]
Looked into this. Think we have to expand your appState as currently it's your todolist spread out. Have it store the `current` list of todo, and `undo` array of todo items. Then your single reducer can handle both list.

**Comment by jaysc** [comment]
I guess we could just instantiate the undo handler in `appStateReducer` but it feels odd.

**Comment by jaysc** [comment]
reducer gets ran twice in strict mode to make it pure. Other options is to store it on the main app component.

**Comment by JonShort** [comment]
It's looking like I'm going to have to wrap the reducer for the DB backend stuff so could do that "trigger undo flow" logic in there

```
     |           | --> Local state
-->  | some hook |
     |           | --> DB
```

Not sure how it's going to work just yet though

**Comment by jaysc** [comment]
Not being able to access the todoItem in the main app is a pain, and the double `useRender` call is annoying.

**Comment by JonShort** [comment]
Added in #13
Enhanced in #14
